services:
    db:
        image: postgres:17.2-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=myapp_development
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.4.1-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
    web:
        build: .
        command: bundle exec rails server -b 0.0.0.0
        volumes:
            - .:/rails
        ports:
            - '3000:3000'
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
            - REDIS_URL=redis://redis:6379/0
            - RAILS_ENV=development
        networks:
            - app-network
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
            - REDIS_URL=redis://redis:6379/0
            - RAILS_ENV=development
        networks:
            - app-network

volumes:
    postgres13:
    redis_data:


networks:
    app-network:
        driver: bridge
